# permissions for end users to view postgresql.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgresql-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgresql-operator
    app.kubernetes.io/part-of: postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-viewer-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - postgresql
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - postgresql/status
  verbs:
  - get
